version: '3.9'

services:
  db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=api
      - DB_USER=postgres
      - DB_PASS=12345
    depends_on:
      - db
  frontend:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"
volumes:
  node-modules: