# Generated by Django 4.0.4 on 2022-05-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='trash_container',
            field=models.CharField(choices=[('Mixed waste', (('color', 'black'),)), ('BIO', (('color', 'brown'),)), ('Paper', (('color', 'blue'),)), ('Glass', (('color', 'green'),)), ('Plastic and metals', (('color', 'yellow'),))], default=None, max_length=5, unique=True),
        ),
        migrations.DeleteModel(
            name='TrashContainer',
        ),
    ]
