# Generated by Django 4.0.4 on 2022-05-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_trash_trash_container'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'material', 'verbose_name_plural': 'materials'},
        ),
        migrations.AlterModelOptions(
            name='trash',
            options={'verbose_name': 'trash', 'verbose_name_plural': 'trashes'},
        ),
        migrations.AlterField(
            model_name='trash',
            name='material',
            field=models.ManyToManyField(blank=True, to='core.material'),
        ),
        migrations.AlterField(
            model_name='trash',
            name='trash_container',
            field=models.CharField(choices=[('mixed waste', 'Mixed waste'), ('bio', 'BIO'), ('paper', 'Paper'), ('glass', 'Glass'), ('plastic and metals', 'Plastic and metals')], default='mixed waste', max_length=18),
        ),
    ]
