# Generated by Django 4.0.4 on 2022-05-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_material_options_alter_trash_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
